# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('make_time', models.DateField(auto_now=True)),
                ('change_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('make_time', models.DateField(auto_now=True)),
                ('change_time', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('task_content', models.CharField(max_length=64)),
                ('make_time', models.DateField(auto_now=True)),
                ('change_time', models.DateField(auto_now_add=True)),
                ('mark', models.CharField(max_length=32)),
                ('course_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Course_content')),
            ],
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('make_time', models.DateField(auto_now=True)),
                ('change_time', models.DateField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Campus')),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.User_type')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='b',
            field=models.ManyToManyField(to='class_app.UserInfo'),
        ),
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Campus'),
        ),
    ]
