# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_auto_20161216_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='change_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='make_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='change_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='make_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='change_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='make_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='change_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='make_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
