# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_auto_20161216_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=32)),
            ],
        ),
    ]
