# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('adviser_name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='sign_up',
            name='school_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
