# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_auto_20161221_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='school_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
