# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0006_chat_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='course_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
