# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0007_chat_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('course_name', models.CharField(blank=True, max_length=32, null=True)),
                ('adviser_name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=64)),
                ('school_id', models.CharField(blank=True, max_length=32, null=True)),
                ('make_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
