# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0008_auto_20161221_1247'),
        ('class_app', '0002_userinfo_source'),
    ]

    operations = [
    ]
