# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0009_merge_20170104_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mark',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
